import Sidebar from '@/components/Sidebar'
import About from './about/page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'twitter clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex min-h-screen max-w-7xl mx-auto'>

          <Sidebar />
        </main>
        {children}
      </body>
    </html>
  )
}
