import './globals.css'

export const metadata = {
  title: 'twitter clone',
  description: 'Generated by create next app',
}




export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json